### ISSUE TITLE
Introducing ID and secret

### ISSUE THREAD

**Issue by JJ** [gwing33/winston-sumologic#1]
I might have missed it, but how do you introduce the ID and secret?

**Comment by gwing33** [comment]
This just uses the Winston Transport: https://github.com/winstonjs/winston/blob/master/docs/transports.md

I haven't used it in over a year, so tread lightly.

**Comment by JJ** [comment]
You still need a particular syntax for those two parameters.

**Comment by gwing33** [comment]
You use it the same way File transport is used... 

``` js
winston.add(WinstonSumoLogic, options)
```

In terms of the ID and secret, I can't say for sure. It has been too long and the project I had built this for, I no longer have access to so I can't reference what I was doing back in the day. As I said, this is probably out of date, I will add a notice on the `.md`
